// Generated by CoffeeScript 1.6.3
(function() {
  var click, clickFunc, completedTutorial, exampleView, exampleViews, highlight, highlightFunc, navigate, navigateFunc, removeHighlight, removeHighlightFunc, shouldSeeTutorial, startTutorial, viewsForIndex, viewsForQuizYourself, viewsForTeachYourself;

  exampleView = function(text, init, cleanup) {
    if (init == null) {
      init = null;
    }
    if (cleanup == null) {
      cleanup = null;
    }
    init = init || function() {};
    cleanup = cleanup || function() {};
    return new Tutorial.ExampleView({
      initAction: init,
      cleanupAction: cleanup,
      exampleText: text
    });
  };

  highlightFunc = function(selector) {
    return function() {
      return highlight(selector);
    };
  };

  highlight = function(selector) {
    return $(selector).css('outline', 'red solid 3px');
  };

  removeHighlightFunc = function(selector) {
    return function() {
      return removeHighlight(selector);
    };
  };

  removeHighlight = function(selector) {
    return $(selector).css('outline', 'none');
  };

  clickFunc = function(selector) {
    return function() {
      return click(selector);
    };
  };

  click = function(selector) {
    var doClick;
    doClick = function() {
      return $(selector).click();
    };
    return setTimeout(doClick, 0);
  };

  navigateFunc = function(path) {
    return function() {
      return navigate(path);
    };
  };

  navigate = function(path) {
    return window.location.pathname = path;
  };

  viewsForIndex = function() {
    var clickLearn_highlightDaysOfCreation, views;
    views = [];
    views.push(exampleView("At BibleRICH, we teach you scriptures with pictures."));
    views.push(exampleView("We recommend you start by <strong>Teach</strong>ing <strong>Yourself</strong>    how to memorize a certain topic or section of the Bible.", highlightFunc('#learn-link'), removeHighlightFunc('#learn-link')));
    clickLearn_highlightDaysOfCreation = function() {
      click('#learn-link');
      return highlight('#days-of-creation-link');
    };
    views.push(exampleView("You should start by learning <strong>The Days of Creation</strong>.", clickLearn_highlightDaysOfCreation, removeHighlightFunc('#days-of-creation-link')));
    views.push(exampleView("Navigating to <strong>The Days of Creation</strong>", navigateFunc('/bible-highlights/genesis/chapter-1.html')));
    return views;
  };

  viewsForTeachYourself = function() {
    var clickQuiz_highlightDays, views;
    views = [];
    views.push(exampleView("The <strong>Teach Yourself</strong> section is where you can learn    about what you want to memorize."));
    views.push(exampleView("The picture should aid your memory.", highlightFunc('#picture'), removeHighlightFunc('#picture')));
    views.push(exampleView("The text explains the memory aids in the picture."));
    views.push(exampleView("If you would like to listen, you can play this recording of the text.", highlightFunc('audio'), removeHighlightFunc('audio')));
    views.push(exampleView("When you're done <strong>Teach</strong>ing <strong>Yourself</strong>\nwhat you want to memorize, you can <strong>Quiz Yourself</strong>.", highlightFunc('#quiz-link'), removeHighlightFunc('#quiz-link')));
    clickQuiz_highlightDays = function() {
      click('#quiz-link');
      return highlight('#days-flashcards');
    };
    views.push(exampleView("We'll go to <strong>The Days of Creation</strong> flashcards.", clickQuiz_highlightDays, removeHighlightFunc('#days-flashcards')));
    views.push(exampleView("Navigating to <strong>The Days of Creation</strong> flashcards.", navigateFunc('/bible-highlights/review/genesis/chapter-1.html')));
    return views;
  };

  viewsForQuizYourself = function() {
    var removeHighlight_clickFlip, views;
    views = [];
    views.push(exampleView("The <strong>Quiz Yourself</strong> section lets you test your    memory with flashcards."));
    views.push(exampleView("You can navigate through the cards with the arrow buttons.", highlightFunc('#flashcards .prev, #flashcards .next'), removeHighlightFunc('#flashcards .prev, #flashcards .next')));
    removeHighlight_clickFlip = function() {
      removeHighlight('.flip');
      return click('.flip');
    };
    views.push(exampleView("You can flip cards with this button.", highlightFunc('.flip'), removeHighlight_clickFlip));
    views.push(exampleView("And you can shuffle using this button.", highlightFunc('.shuffle'), removeHighlightFunc('.shuffle')));
    views.push(exampleView("Now you know the basics! Learn the Days of Creation,    or, if you'd really like to, feel free to explore the rest of the site!", completedTutorial));
    return views;
  };

  shouldSeeTutorial = function() {
    return !Cookies.get('seen-tutorial');
  };

  completedTutorial = function() {
    return Cookies.set('seen-tutorial', true);
  };

  startTutorial = function() {
    Cookies.expire('seen-tutorial');
    if (window.location.pathname === '/') {
      return window.location.reload();
    } else {
      return window.location.pathname = '/';
    }
  };

  exampleViews = function(page) {
    switch (page) {
      case 'index':
        return viewsForIndex();
      case 'teach-yourself':
        return viewsForTeachYourself();
      case 'quiz-yourself':
        return viewsForQuizYourself();
    }
  };

  window.Tutorial = {
    initPage: function(page) {
      var tutorialView;
      if (shouldSeeTutorial()) {
        tutorialView = new Tutorial.TutorialView({
          exampleViews: exampleViews(page)
        });
        tutorialView.on('dismiss-tutorial', function() {
          return completedTutorial();
        });
        return tutorialView.render();
      }
    }
  };

  $('#tutorial').click(startTutorial);

}).call(this);
