safe:        false
port:        4000
baseurl:     /
url: http://localhost:4000

source:      .
destination: ./_site
plugins_dir: ./_plugins
exclude: ["coffee", "scripts", "Gemfile", "Gemfile.lock", "Makefile", "README.md"]
