// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    return Flashcards.init('/bible-highlights/review/exodus/chapter-20.html', [
      {
        img: 'commandments/1.png',
        text: 'I am the Lord, no other gods'
      }, {
        img: 'commandments/2.png',
        text: 'Not make image and bow down to it'
      }, {
        img: 'commandments/3.png',
        text: 'Not take God\'s name in vain'
      }, {
        img: 'commandments/4.png',
        text: 'Sabbath day keep holy'
      }, {
        img: 'commandments/5.png',
        text: 'Honor father and mother'
      }, {
        img: 'commandments/6.png',
        text: 'Not kill'
      }, {
        img: 'commandments/7.png',
        text: 'Not commit adultery'
      }, {
        img: 'commandments/8.png',
        text: 'Not steal'
      }, {
        img: 'commandments/9.png',
        text: 'Not lie'
      }, {
        img: 'commandments/10.png',
        text: 'Not covet'
      }
    ]);
  });

}).call(this);
