// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    return Flashcards.init('/bible-highlights/review/genesis/12-tribes.html', [
      {
        img: 'genesis/chapter-30-reuben.png',
        text: '<h2>See, a Son</h2>'
      }, {
        img: 'genesis/chapter-30-simeon.png',
        text: '<h2>Hear</h2>'
      }, {
        img: 'genesis/chapter-30-levi.png',
        text: '<h2>Join</h2>'
      }, {
        img: 'genesis/chapter-30-judah.png',
        text: '<h2>Praise</h2>'
      }, {
        img: 'genesis/chapter-30-dan.png',
        text: '<h2>Judge</h2>'
      }, {
        img: 'genesis/chapter-30-naphtali.png',
        text: '<h2>Wrestle</h2>'
      }, {
        img: 'genesis/chapter-30-gad.png',
        text: '<h2>Troop</h2>'
      }, {
        img: 'genesis/chapter-30-asher.png',
        text: '<h2>Happy</h2>'
      }, {
        img: 'genesis/chapter-30-issachar.png',
        text: '<h2>Hire</h2>'
      }, {
        img: 'genesis/chapter-30-zebulun.png',
        text: '<h2>Dwell</h2>'
      }, {
        img: 'genesis/chapter-30-joseph.png',
        text: '<h2>Add</h2>'
      }, {
        img: 'genesis/chapter-30-benjamin.png',
        text: '<h2>Son of Right Hand</h2>'
      }
    ]);
  });

}).call(this);
