// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    return Flashcards.init('/bible-highlights/review/genesis/chapters-41-50.html', [
      {
        img: 'genesis/chapter-41.png',
        text: '<h2>Pharaoh&apos;s dream</h2>\
                                            <h3>Manasseh and Ephraim born (ME)</h3>'
      }, {
        img: 'genesis/chapter-42.png',
        text: '<h3>1st trip to Egypt</h3>\
                                            <h2>Spies</h2>\
                                            <h3>2nd - Simeon stays</h3>'
      }, {
        img: 'genesis/chapter-43.png',
        text: '<h2>2nd trip to Egypt</h2>\
                                            <h3>Benjamin goes, gets 5 times more food</h3>'
      }, {
        img: 'genesis/chapter-44.png',
        text: '<h2>The Cup and the Conversation</h2>'
      }, {
        img: 'genesis/chapter-45.png',
        text: '<h2>&quot;I am Joseph&quot; to brothers</h2>\
                                            <h3>weep and kiss</h3>\
                                            <h3>Sends for Jacob</h3>'
      }, {
        img: 'genesis/chapter-46.png',
        text: '<h2>3rd trip to Egypt</h2>\
                                            <h2>All 66 go</h2>\
                                            <h3>Jacob&apos;s descendants Muppim, Huppim, and Ard</h3>'
      }, {
        img: 'genesis/chapter-47.png',
        text: '<h2>Sees Pharaoh</h2>\
                                            <h3>Given best land - Goshen</h3>\
                                            <h3>Joseph acquires land</h3>\
                                            <h4>(Jacob 147 yrs.)</h4>'
      }, {
        img: 'genesis/chapter-48.png',
        text: '<h2>Jacob blesses Manasseh and Ephraim opposite</h2>'
      }, {
        img: 'genesis/chapter-49.png',
        text: '<h2>Jacob blesses his 12 sons</h2>\
                                            <h3>Prophesies (sceptre) and dies</h3>'
      }, {
        img: 'genesis/chapter-50.png',
        text: '<h2>Jacob buried</h2>\
                                            <h3>Out in Canaan</h3>\
                                            <h2>Joseph&apos;s death and burial (110 yrs.)</h2>\
                                            <h3>Will carry bones Out</h3>'
      }
    ]);
  });

}).call(this);
