// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    return Flashcards.init('/bible-highlights/review/genesis/chapters-11-20.html', [
      {
        img: 'genesis/chapter-11.png',
        text: '<h2>Tower of Babel</h2>\
                                            <h3>Generations from Shem to Abram</h3>'
      }, {
        img: 'genesis/chapter-12.png',
        text: '<h2>Abram called out</h2>\
                                            <h3>Says Sarai is sister to Pharaoh</h3>'
      }, {
        img: 'genesis/chapter-13.png',
        text: '<h2>Abram and Lot separate</h2>\
                                            <h3>N,E,S,W and seed as dust promise</h3>'
      }, {
        img: 'genesis/chapter-14.png',
        text: '<h3>Abram rescues Lot</h3>\
                                            <h2>Melchizedek blesses Abram</h2>\
                                            <h4>and the Tithe</h4>'
      }, {
        img: 'genesis/chapter-15.png',
        text: '<h3><em>Seed as Stars</em> promise</h3>\
                                            <h3><em>Strangers</em> and afflicted 400 yrs.</h3>\
                                            <h3>Come out with great <em>substance</em></h3>\
                                            <h3><em>Smoking</em> furnace</h3>\
                                            <h3>burning lamp covenant</h3>'
      }, {
        img: 'genesis/chapter-16.png',
        text: '<h2>Hagar</h2>\
                                            <h2>Ishmael born</h2>'
      }, {
        img: 'genesis/chapter-17.png',
        text: '<h2>Names change</h2>\
                                            <h4>father and mother of many nations</h4>\
                                            <h3>and Circumcision Covenant</h3>'
      }, {
        img: 'genesis/chapter-18.png',
        text: '<h2>3 Strangers ate</h2>\
                                            <h4>Is anything too hard for the Lord?</h4>\
                                            <h3>Not destroy by 10&apos;s</h3>'
      }, {
        img: 'genesis/chapter-19.png',
        text: '<h2>Sodom and Gomorrah</h2>\
                                            <h3>men blinded, wife a pillar</h3>\
                                            <h3>Lot&apos;s daughters - Moab and Benammi</h3>'
      }, {
        img: 'genesis/chapter-20.png',
        text: '<h2>Abraham says Sarah is Sister</h2>\
                                            <h3>Abimelech took her</h3>'
      }
    ]);
  });

}).call(this);
