// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    return Flashcards.init('/bible-highlights/review/genesis/chapters-31-40.html', [
      {
        img: 'genesis/chapter-31.png',
        text: '<h2>Jacob runs</h2>\
                                            <h3>Laban pursues</h3>\
                                            <h3>Rachel steals <em>images</em></h3>'
      }, {
        img: 'genesis/chapter-32.png',
        text: '<h2>Jacab&apos;s time of trouble</h2>\
                                            <h4>I will not let thee go except thou bless me</h4>\
                                            <h3>1st time - Jacob to Israel (name)</h3>'
      }, {
        img: 'genesis/chapter-33.png',
        text: '<h2>Esau Embraces Jacob</h2>'
      }, {
        img: 'genesis/chapter-34.png',
        text: '<h2>Fornication</h2>\
                                            <h4>Shechem with Dinah</h4>\
                                            <h3>the circumcision and the slaughter</h3>'
      }, {
        img: 'genesis/chapter-35.png',
        text: '<h3>5 things buried</h3>\
                                            <h2>Rachel dies bearing Benjamin</h2>\
                                            <h4>2nd time - Jacob to Israel (name)</h4>\
                                            <h4>(Isaac 180 yrs.)</h4>'
      }, {
        img: 'genesis/chapter-36.png',
        text: '<h2>Esau&apos;s descendants</h2>\
                                            <h3>Esau is Edom</h3>'
      }, {
        img: 'genesis/chapter-37.png',
        text: '<h2>3 things happen to Joseph at 17</h2>\
                                            <h3>1 coat of many colors, 2 dreams, sold to Ishmaelites</h3>'
      }, {
        img: 'genesis/chapter-38.png',
        text: '<h2>Tamar plays the harlot</h2>\
                                            <h3>(Judah&apos;s daughter-in-law)</h3>\
                                            <h3>bracelets and twins born</h3>'
      }, {
        img: 'genesis/chapter-39.png',
        text: '<h2>Potiphar&apos;s wife</h2>\
                                            <h4>How then can I do this great <em>wickedness</em> and sin against God</h4>'
      }, {
        img: 'genesis/chapter-40.png',
        text: '<h2>The Butler&apos;s and the Baker&apos;s dreams</h2>'
      }
    ]);
  });

}).call(this);
