// Generated by CoffeeScript 2.0.0-beta8
$(function () {
  return Flashcards.init('/bible-highlights/review/genesis/chapters-21-30.html', [
    {
      img: 'genesis/chapter-21.png',
      text: '<h2>Isaac born</h2>\n                                            <h3>Ishmael and Hagar cast out</h3>'
    },
    {
      img: 'genesis/chapter-22.png',
      text: '<h2>Abraham offers Isaac</h2>\n                                            <h4>God will provide, Jehovah-jireh</h4>\n                                            <h4>seed as stars and sand of sea promise</h4>'
    },
    {
      img: 'genesis/chapter-23.png',
      text: '<h2>Sarah dies</h2>\n                                            <h3>(127 yrs.), buried in a</h3>\n                                            <h2>Cave in Canaan</h2>\n                                            <h3>for 400 shekels of silver</h3>'
    },
    {
      img: 'genesis/chapter-24.png',
      text: '<h2>Isaac marries Rebekah</h2>'
    },
    {
      img: 'genesis/chapter-25.png',
      text: '<h2>Twins born</h2>\n                                            <h2>Esau sells birthright for pot of lentils</h2>\n                                            <h4>Abraham dies (175 yrs.)</h4>'
    },
    {
      img: 'genesis/chapter-26.png',
      text: '<h3>Isaac says Rebekah is <em>sister</em> with Abimelech</h3>\n                                            <h2>well diggings</h2>\n                                            <h4>seed as stars promise</h4>'
    },
    {
      img: 'genesis/chapter-27.png',
      text: '<h2>Rebekah and Jacob deceive Isaac for the blessing</h2>\n                                            <h3>(twin deceiving)</h3>'
    },
    {
      img: 'genesis/chapter-28.png',
      text: '<h2>Jacob&apos;s ladder</h2>\n                                            <h4>N,E,S,W and seed as dust promise</h4>'
    },
    {
      img: 'genesis/chapter-29.png',
      text: '<h3>Laban and Leah deceive Jacob, so 2 brides</h3>\n                                            <h4>Leah bares Rueben, Simeon, Levi, Judah - (Royal Seed Line of Jesus)</h4>'
    },
    {
      img: 'genesis/chapter-30.png',
      text: '<h3>Bilhah - Dan, Naphtali</h3>\n                                            <h3>Zilpah - Gad, Asher</h3>\n                                            <h3>Leah - Issachar, Zebulun</h3>\n                                            <h3>Rachel - <em>Joseph</em>, (Benjamin)</h3>\n                                            <h4>Don&apos;t Nap God Arrives in Zealous Justice, Beware</h4>\n                                            <h3>and spotted animals</h3>'
    }
  ]);
});
