// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    return Flashcards.init('/bible-highlights/review/daniel/chapters-1-12.html', [
      {
        img: 'daniel/chapter-01.png',
        text: '<h3>Diet <small>(10 days)</small></h3>\
                                            <h3>and Wisdom <small>(10 times better)</small></h3>\
                                            <h4>\
                                            <table>\
                                              <tr><td>Daniel</td><td>Belteshazzar</td></tr>\
                                              <tr><td>Hananiah</td><td>Shadrach</td></tr>\
                                              <tr><td>Mishael</td><td>Meshach</td></tr>\
                                              <tr><td>Azariah</td><td>Abednego</td></tr>\
                                            </table>\
                                            </h4>'
      }, {
        img: 'daniel/chapter-02.png',
        text: '<h2>Great Image Dream</h2>\
                                           <h4>gold, silver, brass, iron, iron &amp; clay</h4>\
                                           <h2>Stone hits feet</h2>'
      }, {
        img: 'daniel/chapter-03.png',
        text: '<h2>3 Worthies and The Fiery Furnace</h2>\
                                           <h4>Shadrach, Meshach, Abednego</h4>'
      }, {
        img: 'daniel/chapter-04.png',
        text: '<h2>The Great Tree Dream</h2>\
                                           <h3>a time = a year</h3>'
      }, {
        img: 'daniel/chapter-05.png',
        text: '<h2>Belshazzar&apos;s Banquet<h2>\
                                           <h4>MENE MENE TEKEL UPHARSIN</h4>'
      }, {
        img: 'daniel/chapter-06.png',
        text: '<h2>Daniel and the Lion&apos;s Den</h2>\
                                           <h4>Law written cannot change</h4>'
      }, {
        img: 'daniel/chapter-07.png',
        text: '<h2>4 Beasts are Kings</h2>\
                                           <h4>lion, bear, leopard, dreadful</h4>\
                                           <h2>Judgement</h2>\
                                           <h4>Details of diverse 4th beast who changes times and laws</h4>'
      }, {
        img: 'daniel/chapter-08.png',
        text: '<h3>Ram <small>(great)</small></h3>\
                                           <h3>He-Goat <small>(very great)</small></h3>\
                                           <h3>Little Horn <small>(exceeding great)</small></h3>\
                                           <h3>2300 days</h3>\
                                           <h4>Sanctuary Cleansed</h4>'
      }, {
        img: 'daniel/chapter-09.png',
        text: '<h2>Daniel&apos;s Prayer and Prophecy of Messiah</h2>\
                                           <h3>70 weeks - midst of week</h3>'
      }, {
        img: 'daniel/chapter-10.png',
        text: '<h2>Daniel&apos;s Fast</h2>\
                                           <h4>(3,2,1,0 - coming down)</h4>\
                                           <h2>The Prince, The Angel, and Michael helps</h2>\
                                           <h3>A Prophet - 0 strength, 0 breath</h3>'
      }, {
        img: 'daniel/chapter-11.png',
        text: '<h3>Future in detail</h3>\
                                           <h2>King of North and King of South</h2>\
                                           <h4>(:17 Cleopatra)</h4>'
      }, {
        img: 'daniel/chapter-12.png',
        text: '<h2>Michael Stands Up</h2>\
                                           <h4>time of trouble</h4>\
                                           <h2>(1,2,3,4 going up)</h2>\
                                           <h4>4 ups - Stand up, Sleep awake, Shut up, (many run to and fro) Shall increase)</h4>\
                                           <h4>3 time prophecies - 1/2 (1260), 1290, 1335 days</h4>'
      }
    ]);
  });

}).call(this);
