// Generated by CoffeeScript 2.0.0-beta7
$(function () {
  return Flashcards.init('/bible-highlights/review/daniel/clean-beasts.html', [
    {
      front: '<img src="/img/flashcards/daniel/clean-ram.png" alt="click to see other side"></img>\n              <h3>Ram</h3>',
      back: '<h3>Medo-Persia - 538 B.C.</h3>'
    },
    {
      front: '<img src="/img/flashcards/daniel/clean-goat.png" alt="click to see other side"></img>\n              <h3>He-Goat</h3>',
      back: '<h3>Greece - 331 B.C.</h3>'
    },
    {
      front: '<img src="/img/flashcards/daniel/clean-horn.png" alt="click to see other side"></img>\n              <h3>Little Horn</h3>',
      back: '<h3>Rome - 168 B.C.</h3>'
    }
  ]);
});
