// Generated by CoffeeScript 2.0.0-beta7
$(function () {
  return Flashcards.init('/bible-highlights/review/daniel/hebrew-boys.html', [
    {
      front: '<img src="/img/flashcards/daniel/boys-daniel.png" alt="click to see other side"></img>',
      back: '<img src="/img/flashcards/daniel/boys-belteshazzar.png" alt="click to see other side"></img>'
    },
    {
      front: '<img src="/img/flashcards/daniel/boys-hananiah.png" alt="click to see other side"></img>',
      back: '<img src="/img/flashcards/daniel/boys-shadrach.png" alt="click to see other side"></img>'
    },
    {
      front: '<img src="/img/flashcards/daniel/boys-mishael.png" alt="click to see other side"></img>',
      back: '<img src="/img/flashcards/daniel/boys-meshach.png" alt="click to see other side"></img>'
    },
    {
      front: '<img src="/img/flashcards/daniel/boys-azariah.png" alt="click to see other side"></img>',
      back: '<img src="/img/flashcards/daniel/boys-abednego.png" alt="click to see other side"></img>'
    }
  ]);
});
