// Generated by CoffeeScript 2.0.0-beta7
$(function () {
  return Flashcards.init('/bible-highlights/review/daniel/writing-on-wall.html', [
    {
      front: '<img src="/img/flashcards/daniel/writing-on-wall.png" alt="click to see other side"></img>\n              <h3>MENE</h3>',
      back: '<h3>Numbered</h3>'
    },
    {
      front: '<img src="/img/flashcards/daniel/writing-on-wall.png" alt="click to see other side"></img>\n              <h3>TEKEL</h3>',
      back: '<h3>Weighed and Wanting</h3>'
    },
    {
      front: '<img src="/img/flashcards/daniel/writing-on-wall.png" alt="click to see other side"></img>\n              <h3>UPHARSIN</h3>\n              <h4>(PERES)</h4>',
      back: '<h3>Divided and Given to the Medes and Persians</h3>'
    }
  ]);
});
